# Generated by Django 5.0.7 on 2024-08-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomy',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='nomy',
            name='image',
            field=models.ImageField(upload_to='nomy/images/'),
        ),
    ]
