# Generated by Django 5.0.7 on 2024-08-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomy', '0002_alter_nomy_description_alter_nomy_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomy',
            name='genre',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='nomy',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nomy',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
